services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - auth-service
      - product-service
      - order-service

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "4001:4001"

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    ports:
      - "4002:4002"

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - "4003:4003"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # main RabbitMQ
      - "15672:15672" # management UI  
    restart: always      
